services:
  app:
    image: ghcr.io/cachix/devenv/devcontainer:latest
    volumes:
      - ..:/workspace:cached
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stayspot
      PG_URI: postgresql://postgres:postgres@postgres:5432/stayspot
      MONGO_URI: mongodb://mongo:27017/stayspot
      MONGO_DB: stayspot
    depends_on:
      mongo:
        condition: service_healthy
      postgres:
        condition: service_healthy

  mongo:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test:
        ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 5s
      timeout: 5s
      retries: 20

  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stayspot
    volumes:
      - postgres-data:/var/lib/postgresql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d stayspot"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  mongo-data:
  postgres-data:
